
name: Run main.py

# on:
#   schedule:
#     - cron: '0 * * * *' # every hour, on the hour


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository content to the GitHub runner
      - name: Checkout repository content
        uses: actions/checkout@v2

      # Step 2: Set up Python (specify the version needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies from requirements.txt
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script and log output to status.log
      - name: Execute Python script (main.py) and log output
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          WHTR_API_KEY: ${{ secrets.WHTR_API_KEY }}
        run: |
          echo "Job started at $(date)" | tee -a status.log
          python main.py 2>&1 | tee -a status.log
          echo "Job ended at $(date)" | tee -a status.log

      # Step 5: Upload the log as an artifact
      - name: Upload status.log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: status-log
          path: status.log
